### ISSUE TITLE
Create stemcell failed: unable to find AKI

### ISSUE THREAD

**Issue by arekkas** [cloudfoundry-community/bosh-bootstrap#305]
I created a EC2 instance (ubuntu) in the eu-central-1 region with an elastic ip, ssh'd into it and ran:

```
sudo apt-get update
sudo apt-get install ruby 1.9.3
sudo apt-get install ruby-dev 1.9.3
sudo apt-get install libxml2 libxml2-dev libsqlite3-dev make libxslt1-dev g++ libpq-dev libmysqld-dev libmysqlclient-dev
sudo gem install bundle
sudo gem install bosh-bootstrap
```

After that I tried to deploy micro bosh on AWS, which resulted in: `Uploading stemcellcreate stemcell failed: unable to find AKI:`

```
bosh-bootstrap deploy
1. AWS
2. OpenStack
3. vSphere
Choose your infrastructure: 1

Using provider AWS

Access key: ****
Secret key: ****

1. *US East (Northern Virginia) Region (us-east-1)
2. US West (Oregon) Region (us-west-2)
3. US West (Northern California) Region (us-west-1)
4. EU (Ireland) Region (eu-west-1)
5. EU (Frankfurt) Region (eu-central-1)
6. Asia Pacific (Singapore) Region (ap-southeast-1)
7. Asia Pacific (Sydney) Region (ap-southeast-2)
8. Asia Pacific (Tokyo) Region (ap-northeast-1)
9. South America (Sao Paulo) Region (sa-east-1)
10. China (Beijing) Region (cn-north-1)
Choose AWS region: 5

Confirming: Using AWS EC2/eu-central-1
1. subnet-f3fb1b88 (172.31.0.0/20)
2. subnet-0834f561 (172.31.16.0/20)
Choose a subnet: 2

Choose IP |172.31.16.4| 

Confirming: Using address 172.31.16.4
Reusing security group ssh-vpc-53e9153a for the VPC
 -> no additional ports opened
Created security group dns-server-vpc-53e9153a for the VPC
 -> opened dns-server-vpc-53e9153a ports UDP 53..53 from IP range 0.0.0.0/0
Created security group bosh-vpc-53e9153a for the VPC
 -> opened bosh-vpc-53e9153a ports TCP 4222..4222 from IP range 0.0.0.0/0
 -> opened bosh-vpc-53e9153a ports TCP 6868..6868 from IP range 0.0.0.0/0
 -> opened bosh-vpc-53e9153a ports TCP 25250..25250 from IP range 0.0.0.0/0
 -> opened bosh-vpc-53e9153a ports TCP 25555..25555 from IP range 0.0.0.0/0
 -> opened bosh-vpc-53e9153a ports TCP 25777..25777 from IP range 0.0.0.0/0
Destroying key pair firstbosh... done
Acquiring a key pair firstbosh... done

Confirming: Using key pair firstbosh
Determining stemcell image/file to use... curl -O 'https://bosh-jenkins-artifacts.s3.amazonaws.com/bosh-stemcell/aws/bosh-stemcell-2847-aws-xen-ubuntu-trusty-go_agent.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  442M  100  442M    0     0  12.7M      0  0:00:34  0:00:34 --:--:-- 16.5M
/home/ubuntu/bosh/deployments/firstbosh/bosh-stemcell-2847-aws-xen-ubuntu-trusty-go_agent.tgz
bosh micro deployment firstbosh
WARNING! Your target has been changed to `https://172.31.16.4:25555'!
Deployment set to '/home/ubuntu/bosh/deployments/firstbosh/micro_bosh.yml'
bosh -n micro deploy --update-if-exists /home/ubuntu/bosh/deployments/firstbosh/bosh-stemcell-2847-aws-xen-ubuntu-trusty-go_agent.tgz

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-aws-xen-ubuntu-trusty-go_agent
Version: 2847

  Started deploy micro bosh
  Started deploy micro bosh > Unpacking stemcell. Done (00:00:07)
  Started deploy micro bosh > Uploading stemcellcreate stemcell failed: unable to find AKI:
/var/lib/gems/1.9.1/gems/bosh_aws_cpi-1.2847.0/lib/cloud/aws/aki_picker.rb:15:in `pick'
/var/lib/gems/1.9.1/gems/bosh_aws_cpi-1.2847.0/lib/cloud/aws/stemcell_creator.rb:100:in `image_params'
/var/lib/gems/1.9.1/gems/bosh_aws_cpi-1.2847.0/lib/cloud/aws/stemcell_creator.rb:24:in `create'
/var/lib/gems/1.9.1/gems/bosh_aws_cpi-1.2847.0/lib/cloud/aws/cloud.rb:425:in `block in create_stemcell'
/var/lib/gems/1.9.1/gems/bosh_common-1.2847.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/lib/gems/1.9.1/gems/bosh_aws_cpi-1.2847.0/lib/cloud/aws/cloud.rb:405:in `create_stemcell'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:228:in `block (2 levels) in create_stemcell'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:85:in `step'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:227:in `block in create_stemcell'
/usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:213:in `create_stemcell'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:118:in `create'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:98:in `block in create_deployment'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:92:in `with_lifecycle'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/deployer/instance_manager.rb:98:in `create_deployment'
/var/lib/gems/1.9.1/gems/bosh_cli_plugin_micro-1.2847.0/lib/bosh/cli/commands/micro.rb:179:in `perform'
/var/lib/gems/1.9.1/gems/bosh_cli-1.2847.0/lib/cli/command_handler.rb:57:in `run'
/var/lib/gems/1.9.1/gems/bosh_cli-1.2847.0/lib/cli/runner.rb:56:in `run'
/var/lib/gems/1.9.1/gems/bosh_cli-1.2847.0/lib/cli/runner.rb:16:in `run'
/var/lib/gems/1.9.1/gems/bosh_cli-1.2847.0/bin/bosh:7:in `<top (required)>'
/usr/local/bin/bosh:23:in `load'
/usr/local/bin/bosh:23:in `<main>'
/usr/lib/ruby/1.9.1/rake/file_utils.rb:53:in `block in create_shell_runner': Command failed with status (1): [bosh -n micro deploy --update-if-exists /h...] (RuntimeError)
	from /usr/lib/ruby/1.9.1/rake/file_utils.rb:45:in `call'
	from /usr/lib/ruby/1.9.1/rake/file_utils.rb:45:in `sh'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/cli/helpers/bundle.rb:18:in `block in run'
	from /var/lib/gems/1.9.1/gems/bundler-1.8.2/lib/bundler.rb:247:in `block in with_clean_env'
	from /var/lib/gems/1.9.1/gems/bundler-1.8.2/lib/bundler.rb:234:in `with_original_env'
	from /var/lib/gems/1.9.1/gems/bundler-1.8.2/lib/bundler.rb:240:in `with_clean_env'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/cli/helpers/bundle.rb:16:in `run'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/microbosh.rb:54:in `block in deploy_or_update'
	from /usr/lib/ruby/1.9.1/fileutils.rb:125:in `chdir'
	from /usr/lib/ruby/1.9.1/fileutils.rb:125:in `cd'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/microbosh.rb:52:in `deploy_or_update'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/microbosh.rb:42:in `block in deploy'
	from /usr/lib/ruby/1.9.1/fileutils.rb:125:in `chdir'
	from /usr/lib/ruby/1.9.1/fileutils.rb:125:in `cd'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/microbosh.rb:40:in `deploy'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/cli/commands/deploy.rb:77:in `perform_microbosh_deploy'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/cli/commands/deploy.rb:24:in `perform'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/lib/bosh-bootstrap/thor_cli.rb:11:in `deploy'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.16.1/bin/bosh-bootstrap:13:in `<top (required)>'
	from /usr/local/bin/bosh-bootstrap:23:in `load'
	from /usr/local/bin/bosh-bootstrap:23:in `<main>'
```

I've also tried to use the elastic ip but it didn't change anything:

```
Choose IP |172.31.0.4| 54.93.119.***

Confirming: Using address 54.93.119.***
```

**Comment by drnic** [comment]
I think this is an upstream bosh question. I've not seen this issue before, sorry! cc @cppforlife

**Comment by arekkas** [comment]
Should I create a separate issue in the bosh repository?

**Comment by drnic** [comment]
Yes I think so. I'm sorry in advance Dmitriy @cppforlife spots it as a bosh-bootstrap issue and throws it back here; but hopefully that's not the case. :)

**Comment by arekkas** [comment]
ok, thank you for your help :)
