### ISSUE TITLE
bosh-bootstrap fails on kernal_require.rb

### ISSUE THREAD

**Issue by HifzaK** [cloudfoundry-community/bosh-bootstrap#321]
Hi,

I am trying to deploy cloud foundry on openstack using travelling bosh. When I enter the command "bosh-bootstrap deploy", it fails at 

```/home/..../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/..../.rvm/gems/ruby-2.2.1/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/cli/helpers/bundle.rb:5:in `<top (required)>'
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/..../.rvm/gems/ruby-2.2.1/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/cli/helpers.rb:3:in `<top (required)>'
	from /home/..../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap/microbosh.rb:2:in `<top (required)>'
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/bosh-bootstrap-0.16.2/lib/bosh-bootstrap.rb:20:in `<top (required)>'
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/.../.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/bosh-bootstrap-0.16.2/bin/bosh-bootstrap:6:in `<top (required)>'
	from /home/.../.rvm/gems/ruby-2.2.1/bin/bosh-bootstrap:23:in `load'
	from /home/..../.rvm/gems/ruby-2.2.1/bin/bosh-bootstrap:23:in `<main>'
	from /home/.../.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/.../.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>```

Does anyone have any ideas?

**Comment by drnic** [comment]
Sorry, try "gem install bundler" first

**Comment by HifzaK** [comment]
Thanks, it worked.

**Comment by HifzaK** [comment]
Is there a way to resolve the following issue without running stack.sh again

```create stemcell failed: Invalid OpenStack cloud properties: #<Membrane::SchemaValidationError: { openstack => { api_key => Expected instance of String, given an instance of Fixnum } }>:```

**Comment by drnic** [comment]
Perhaps can you create a new issue for this so it doesn't get lost?

**Comment by HifzaK** [comment]
Sure.
