### ISSUE TITLE
bosh bootstrap fails on starting tcp server

### ISSUE THREAD

**Issue by HifzaK** [cloudfoundry-community/bosh-bootstrap#323]
Hi,

I am trying to deploy cloud foundry on openstack using traveling bosh. It fails at 

```
Stemcell info
-------------
Name:    bosh-openstack-kvm-ubuntu-trusty-go_agent
Version: 3143

/home/..../.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8/lib/eventmachine.rb:534:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
	from /home/..../.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8/lib/eventmachine.rb:534:in `start_server'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/backends/tcp_server.rb:16:in `connect'
	from /home/..../.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/backends/base.rb:55:in `block in start'
	from /home/..../.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
	from /home/..../.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
	from /home/..../.rvm/gems/ruby-2.2.1/gems/bosh-registry-1.3140.0/lib/bosh/registry/runner.rb:34:in `start_http_server'
	from /home/.../.rvm/gems/ruby-2.2.1/gems/bosh-registry-1.3140.0/lib/bosh/registry/runner.rb:18:in `run'
	from /home/..../.rvm/gems/ruby-2.2.1/gems/bosh-registry-1.3140.0/bin/bosh-registry:28:in `<top (required)>'
	from /home/.../.rvm/gems/ruby-2.2.1/bin/bosh-registry:23:in `load'
	from /home/.../.rvm/gems/ruby-2.2.1/bin/bosh-registry:23:in `<main>'
	from /home/..../.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/.../.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Does anybody how to get rid of this error?

**Comment by drnic** [comment]
I would avoid traveling bosh at the moment, sadly. It packages an old version of bosh cli that might not work with latest stemcells. Try installing Ruby via rvm.io and then install bosh-bootstrap and try again

**Comment by HifzaK** [comment]
I am getting the same error using bosh-bootstrap. Any suggestions?

**Comment by drnic** [comment]
This is your ticket I think
