### ISSUE TITLE
"gem install bosh-bootstrap" hangs forever

### ISSUE THREAD

**Issue by fabiodbr** [cloudfoundry-community/bosh-bootstrap#327]
I don't know whether this is a "gem" problem or some kind of gem repository problem, but the gem install always hang when trying to install bosh-bootstrap. I tried manually to install bosh-bootstrap with "gem install" and since version 0.17.0 it never finish. I tried several times and waited for hours without success.
Older versions like 0.16.1 installs successfully.
Is there anything I'm missing?

**Comment by fabiodbr** [comment]
After 3 hours of "gem install bundler bosh-bootstrap --no-ri --no-rdoc --verbose" this is the return:

---

GET https://api.rubygems.org/api/v1/dependencies?gems=cdb-full
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=tokyocabinet
200 OK
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies nokogiri (~> 1.5.0) and nokogiri (>= 1.4.1)
  Activated nokogiri-1.4.1
  which does not match conflicting dependency (~> 1.5.0)

  Conflicting dependency chains:
    bosh-bootstrap (>= 0), 0.18.0 activated, depends on
    rbvmomi (>= 0), 1.0.1 activated, depends on
    nokogiri (>= 1.4.1), 1.4.1 activated

  versus:
    bosh-bootstrap (>= 0), 0.18.0 activated, depends on
    fog (~> 1.11), 1.11.0 activated, depends on
    nokogiri (~> 1.5.0)

---

I've tried with ruby versions 2.1.5p273 and 1.9.3, and gem vesion 2.4.3

**Comment by ramonskie** [comment]
same issue here

**Comment by drnic** [comment]
Hmm, strange that everyone on this thread is getting this issue. v0.18.1 was released in December to loosen the fog dependency; but I see 0.17.0 and v0.18.0 being attempted.

I could not reproduce when I ran:

```
rvm @test-bootstrap --create
gem install bosh-bootstrap
```

This successfully installed v0.18.1:

```
Fetching: bosh-bootstrap-0.18.1.gem (100%)
Successfully installed bosh-bootstrap-0.18.1
```

Can you try forcing the install of v0.18.1?

```
gem install bosh-bootstrap -v 0.18.1
```

**Comment by ramonskie** [comment]
on ruby 2.3.0 it works
on ruby 2.2.3 or lower it fails

so we need to set the minimum requirements in the doc :+1:

**Comment by ramonskie** [comment]
after the installation on 2.3.0 the gem rake is missing

so it results in the following error

```
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rake (LoadError)
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bosh-bootstrap-0.18.1/lib/bosh-bootstrap/cli/helpers/bundle.rb:2:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bosh-bootstrap-0.18.1/lib/bosh-bootstrap/cli/helpers.rb:3:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bosh-bootstrap-0.18.1/lib/bosh-bootstrap/microbosh.rb:2:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bosh-bootstrap-0.18.1/lib/bosh-bootstrap.rb:20:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bosh-bootstrap-0.18.1/bin/bosh-bootstrap:6:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.3.0/bin/bosh-bootstrap:23:in `load'
	from /home/ubuntu/.rbenv/versions/2.3.0/bin/bosh-bootstrap:23:in `<main>'
```

after gem install rake the issue seems to be resolved
found solution at https://github.com/test-kitchen/busser-serverspec/issues/28

**Comment by tomsherrod** [comment]
Ran into the same thing. 
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.1.8 (2015-12-16 patchlevel 440) [x86_64-linux]

Used gem install bundler bosh-bootstrap:0.16.2 successfully.
Interesting part, on a running machine 0.18.0 is actually on it so updates work and not fresh installs?

**Comment by fabiodbr** [comment]
Yes @drnic, it worked on:

> - RUBYGEMS VERSION: 2.5.1
> - RUBY VERSION: 2.3.0

And I agree with @ramonskie, I think this should be documented.

Thank you.
